# Generated by Django 5.2 on 2025-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
