# Generated by Django 5.2 on 2025-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_booking_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
