# Generated by Django 5.2 on 2025-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
