# Generated by Django 5.2 on 2025-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_slug',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
