# Generated by Django 5.2 on 2025-05-21 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationlink',
            name='link',
        ),
        migrations.AddField(
            model_name='verificationlink',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
