# Generated by Django 5.2 on 2025-05-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_booking_status'),
        ('core', '0002_remove_verificationlink_link_verificationlink_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlink',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.booking'),
            preserve_default=False,
        ),
    ]
