# Generated by Django 5.2 on 2025-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verificationlink_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlink',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
